# Generated by Django 2.1.5 on 2019-10-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('blond', 'Blond'), ('black', 'Black'), ('brown', 'Brown'), ('red', 'Red')], default='blond', max_length=10, null=True),
        ),
    ]
